name: "Deploy to ECS Platform"
description: "Deploy a service using platform Terraform modules"

inputs:
  environment:
    required: true
    description: "Target environment (dev, prod, etc.)"

  service_path:
    required: true
    description: "Path to the service directory (e.g., SampleSolution/Service1)"

  image_uri:
    required: true
    description: "Docker image URI to deploy"

  aws_region:
    description: "AWS region for deployment"
    required: false
    default: "eu-west-2"

runs:
  using: "docker"
  image: "docker.io/nehamictech/iac-image:latest"
  env:
    ENVIRONMENT: ${{ inputs.environment }}
    IMAGE_URI: ${{ inputs.image_uri }}
    SERVICE_PATH: ${{ inputs.service_path }}
    AWS_REGION: ${{ inputs.aws_region }}
