port: 8080
autoscale: false
task_count:
  min: 1
  max: 1
env_vars:
  ASPNETCORE_ENVIRONMENT: Development

health_check:
  path: "/health"
  interval: 30
  timeout: 5
  healthy_threshold: 2
  unhealthy_threshold: 2
