service:
  name: service3
  version: 1.0.0
  type: api
  cpu: 256
  memory: 512
  platform_version: "LATEST"

health_check:
  path: "/health"
  interval: 30
  timeout: 5
  healthy_threshold: 2
  unhealthy_threshold: 2
