service:
  name: service1
  version: 1.0.0
  type: app
  task_count:
    min: 1
    max: 1
  cpu: 256
  memory: 512
  logs_retention: 1
  container_port: 8080
  health_check_path: "/health"
  deploy: true
  env_vars:
    ASPNETCORE_ENVIRONMENT: Development
    SERVICE2_URL: http://service2.dev.local:8080
    SERVICE3_URL: http://service3.dev.local:8080
