port: 80
autoscale: false
task_count:
  min: 1
  max: 1

env_vars:
  ASPNETCORE_ENVIRONMENT: Development
  SERVICE2_URL: http://service2.dev.local:8080
  SERVICE3_URL: http://service3.dev.local:8080

cloudwatch:
  retention_days: 1
