name: Build & Deploy to ECS

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Service1]

    env:
      CODE_ROOT: src
      SOLUTION_NAME: SampleAspireSolution

    steps:
      - name: ♻️ Cache terraform plugins
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: terraform-${{ runner.os }}-

      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🔧 Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: 🧠 Infer environment from branch
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          if [[ "$BRANCH" == "main" ]]; then
            ENVIRONMENT="prod"
          elif [[ "$BRANCH" == "stg" ]]; then
            ENVIRONMENT="stg"
          else
            ENVIRONMENT="dev"
          fi
          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_ENV"

      - name: ✨ Generate lowercase service name
        id: name
        run: echo "lower=$(echo '${{ matrix.service }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: 🏷️ Read version from service.yaml
        id: config
        run: |
          IMAGE_TAG=$(yq '.service.version // "latest"' "$CODE_ROOT/${{ matrix.service }}/.iac/${ENVIRONMENT}.yaml")
          echo "version=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: 🕵️ Detect code changes or force rebuild
        id: changes
        run: echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: 📦 Restore dependencies
        run: dotnet restore "${{ env.SOLUTION_NAME }}.sln"

      - name: 🛠️ Build code
        if: steps.changes.outputs.changed == 'true'
        run: |
          dotnet build "$CODE_ROOT/${{ matrix.service }}/${{ matrix.service }}.csproj" --no-restore --configuration Release

      - name: ⏭️ Skip .NET build (no changes)
        if: steps.changes.outputs.changed == 'false'
        run: echo "No changes in code. Skipping .NET build."

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🏗️ Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names "${{ steps.name.outputs.lower }}" || \
          aws ecr create-repository --repository-name "${{ steps.name.outputs.lower }}"

      - name: 🐳 Build Docker image
        if: steps.changes.outputs.changed == 'true'
        run: |
          IMAGE_NAME="${{ secrets.ECR_REGISTRY }}/${{ steps.name.outputs.lower }}"
          IMAGE_TAG="${{ steps.config.outputs.version }}"
          docker build -t "$IMAGE_NAME:$IMAGE_TAG" -f "$CODE_ROOT/${{ matrix.service }}/Dockerfile" .

      - name: ⏭️ Skip Docker build (no changes)
        if: steps.changes.outputs.changed == 'false'
        run: echo "No changes in code. Skipping Docker build."

      - name: 🚀 Push Docker image to ECR
        if: steps.changes.outputs.changed == 'true'
        run: |
          IMAGE_NAME="${{ secrets.ECR_REGISTRY }}/${{ steps.name.outputs.lower }}"
          IMAGE_TAG="${{ steps.config.outputs.version }}"
          docker push "$IMAGE_NAME:$IMAGE_TAG"

      - name: 🚀 Deploy to ECS
        uses: ./.github/actions/ecr-deploy
        with:
          environment: ${{ env.ENVIRONMENT }}
          service_path: ${{ env.CODE_ROOT }}/${{ matrix.service }}
          image_uri: ${{ secrets.ECR_REGISTRY }}/${{ steps.name.outputs.lower }}:${{ steps.config.outputs.version }}
        env:
          ACTION: apply
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GH_PLATFORM_TOKEN }}
