name: Build & Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (dev, prod, etc.)"
        required: true
        default: "dev"

jobs:
  build:
    name: Build and Deploy Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Service1, Service2]
    env:
      CODE_ROOT: src
      SOLUTION_NAME: SampleAspireSolution
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: ♻️ Cache terraform plugins
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: terraform-${{ runner.os }}-

      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🔧 Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: 📦 Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_NAME }}.sln

      - name: ✨ Generate lowercase service names
        run: echo "SERVICE_NAME_LOWER=$(echo '${{ matrix.service }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: 🏷️ Read version from service.yaml
        id: config
        run: |
          IMAGE_TAG=$(yq '.service.version // "latest"' ${{ env.CODE_ROOT }}/${{ matrix.service }}/.iac/service.yaml)
          echo "version=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
        env:
          CODE_ROOT: ${{ env.CODE_ROOT }}

      - name: 🛠️ Build code
        run: |
          dotnet build ${{ env.CODE_ROOT }}/${{ matrix.service }}/${{ matrix.service }}.csproj --no-restore --configuration Release

      - name: 🔐 Log in to ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 🏗️ Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names "$SERVICE_NAME_LOWER" || \
          aws ecr create-repository --repository-name "$SERVICE_NAME_LOWER"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: 🐳 Build Docker image
        run: |
          IMAGE_NAME="${ECR_REGISTRY}/${SERVICE_NAME_LOWER}"
          IMAGE_TAG="${{ steps.config.outputs.version }}"
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f ${{ env.CODE_ROOT }}/${{ matrix.service }}/Dockerfile .

      - name: 🚀 Push Docker image to ECR
        run: |
          IMAGE_NAME="${ECR_REGISTRY}/${SERVICE_NAME_LOWER}"
          IMAGE_TAG="${{ steps.config.outputs.version }}"
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: 🚀 Deploy to ECS
        uses: ./.github/actions/ecr-deploy
        with:
          environment: ${{ github.event.inputs.environment }}
          service_path: ${{ env.CODE_ROOT }}/${{ matrix.service }}
          image_uri: ${{ env.ECR_REGISTRY }}/${{ env.SERVICE_NAME_LOWER }}:${{ steps.config.outputs.version }}
        env:
          ACTION: apply
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GH_PLATFORM_TOKEN }}
