name: Build & Deploy to ECS

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Service1]

    defaults:
      run:
        shell: bash

    env:
      CODE_ROOT: src
      SOLUTION_NAME: SampleAspireSolution

    steps:
      - name: ♻️ Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: terraform-${{ runner.os }}-

      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: 🧠 Infer environment from branch
        run: |
          case "${GITHUB_REF_NAME}" in
            main) ENVIRONMENT="prod" ;;
            stg) ENVIRONMENT="stg" ;;
            *) ENVIRONMENT="dev" ;;
          esac
          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_ENV"

      - name: ✨ Generate lowercase service name
        id: name
        run: echo "lower=$(echo '${{ matrix.service }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: 🏷️ Read version from service.yaml
        id: config
        run: |
          VERSION=$(yq '.service.version // "latest"' "$CODE_ROOT/${{ matrix.service }}/.iac/${ENVIRONMENT}.yaml" || echo "latest")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: 🕵️ Detect code changes or force rebuild
        id: changes
        run: echo "changed=true" >> "$GITHUB_OUTPUT" # Placeholder for actual logic

      - name: 📦 Restore .NET dependencies
        run: dotnet restore "${{ env.SOLUTION_NAME }}.sln"

      - name: 🛠️ Build .NET project
        run: dotnet build "$CODE_ROOT/${{ matrix.service }}/${{ matrix.service }}.csproj" --no-restore --configuration Release

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🏗️ Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "${{ steps.name.outputs.lower }}" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "${{ steps.name.outputs.lower }}"

      - name: 🔐 Authenticate Docker to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: 🐳 Build Docker image
        run: |
          IMAGE_NAME="${{ secrets.ECR_REGISTRY }}/${{ steps.name.outputs.lower }}"
          IMAGE_TAG="${{ steps.config.outputs.version }}"
          docker build -t "$IMAGE_NAME:$IMAGE_TAG" -f "$CODE_ROOT/${{ matrix.service }}/Dockerfile" .

      - name: 🚀 Push Docker image to ECR
        run: |
          IMAGE_NAME="${{ secrets.ECR_REGISTRY }}/${{ steps.name.outputs.lower }}"
          IMAGE_TAG="${{ steps.config.outputs.version }}"
          docker push "$IMAGE_NAME:$IMAGE_TAG"

      - name: 📤 Deploy to ECS
        uses: ./.github/actions/ecr-deploy
        env:
          IMAGE_URI: ${{ secrets.ECR_REGISTRY }}/${{ steps.name.outputs.lower }}:${{ steps.config.outputs.version }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          SERVICE_PATH: ${{ env.CODE_ROOT }}/${{ matrix.service }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GH_PLATFORM_TOKEN }}
