name: Destroy deployed Services

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (dev, prod, etc.)"
        required: true
        default: "dev"

jobs:
  build:
    name: Destroy Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #service: [Service1, Service2, Service3]
        service: [Service3]

    env:
      CODE_ROOT: src
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: ♻️ Cache terraform plugins
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: terraform-${{ runner.os }}-

      - name: 🚀 Update ECS
        uses: ./.github/actions/ecr-deploy
        with:
          environment: ${{ github.event.inputs.environment }}
          service_path: ${{ env.CODE_ROOT }}/${{ matrix.service }}

        env:
          ACTION: destroy
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GH_PLATFORM_TOKEN }}
